#if !canImport(ObjectiveC)
import XCTest

extension TunisiaTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TunisiaTests = [
        ("testSwiftVersionRegex", testSwiftVersionRegex),
        ("testXcodeVersion", testXcodeVersion),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TunisiaTests.__allTests__TunisiaTests),
    ]
}
#endif
