name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make installables
    - name: Run tests
      run: make test
    - name: Check linux main
      run: make linuxmain && git diff --exit-code Tests